
name: 'dbt_groupp'
version: '1.0.0'

profile: 'dbt_groupp'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_groupp:
    +materialized: view
    +schema: staging
        
    src:
      +materialized: ephermal
      +schema: staging

    dim:
      +schema: refined

    fct:
      +schema: refined
      
    mart:
      +schema: marts