version: 2

models:
  - name: fct_job_ads
    description: fact table combining job ads with dimension ref's and measures.
    columns:
      - name: occupation_id
        description: surrogate key to dim_occupation
        tests:
          - not_null
          - relationships:
              field: occupation_id
              to: dim_occupation
    
      - name: job_details_id
        description: surrogate key to dim_job_details
        tests:
          - not_null
          - relationships:
              field: dim_job_details
              to: dim_job_details

      - name: employer_id
        description: surrogate key to dim_employer
        tests:
          - not_null
          - relationships:
              field: employer_id
              to: dim_employer

      - name: auxilliary_attributes_id
        description: surrogate key to dim_auxilliary_attributes
        tests:
          - not_null
          - relationships:
              field: auxilliary_attributes_id
              to: dim_auxilliary_attributes

      - name: vacancies
        description: number of vacancies
        tests:
          - not_null

      - name: relevance
        description: relevance score from the API

      - name: deadline
        description: deadline until last day of application
      